CREATE TABLE IF NOT EXISTS users (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('customer','admin') NOT NULL DEFAULT 'customer',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY,
 user_id INT UNSIGNED NOT NULL,
 expires_at DATETIME NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS products (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 slug VARCHAR(150) NOT NULL UNIQUE,
 name VARCHAR(150) NOT NULL,
 category VARCHAR(60) NOT NULL,
 occasion VARCHAR(60) NOT NULL,
 price INT UNSIGNED NOT NULL,
 old_price INT UNSIGNED NULL,
 image VARCHAR(500) NOT NULL,
 description TEXT NOT NULL,
 flowers VARCHAR(255) NOT NULL,
 badge VARCHAR(40) NULL,
 stock INT UNSIGNED NOT NULL DEFAULT 20,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS orders (
 id CHAR(12) PRIMARY KEY,
 user_id INT UNSIGNED NULL,
 recipient VARCHAR(100) NOT NULL,
 phone VARCHAR(20) NOT NULL,
 email VARCHAR(190) NOT NULL,
 address VARCHAR(500) NOT NULL,
 delivery_date DATE NOT NULL,
 message VARCHAR(1000) NOT NULL DEFAULT '',
 subtotal INT UNSIGNED NOT NULL,
 shipping INT UNSIGNED NOT NULL,
 total INT UNSIGNED NOT NULL,
 status ENUM('pending','confirmed','preparing','shipping','delivered','cancelled') NOT NULL DEFAULT 'pending',
 payment_method ENUM('cod') NOT NULL DEFAULT 'cod',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS order_items (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id CHAR(12) NOT NULL,
 product_id INT UNSIGNED NOT NULL,
 name VARCHAR(150) NOT NULL,
 image VARCHAR(500) NOT NULL,
 price INT UNSIGNED NOT NULL,
 quantity INT UNSIGNED NOT NULL,
 FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
 FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS inquiries (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(190) NOT NULL,
 message TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS subscribers (
 email VARCHAR(190) PRIMARY KEY,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
