import { useState, type ChangeEvent } from "react";
import { Pencil, Plus, Trash2, ImagePlus } from "lucide-react";
import { PageHeading } from "../../components";
import { AdminNav } from "./AdminNav";
import { articles as sampleArticles } from "../Content";
const KEY = "nha-hoa-articles";
type Story = { slug: string; title: string; category: string; intro: string; image: string; sections: string[][] };
const read = (): Story[] => { try { const saved = JSON.parse(localStorage.getItem(KEY) || "null"); return Array.isArray(saved) && saved.length ? saved : sampleArticles.map((a) => ({ slug: a.slug, title: a.title, category: a.category, intro: a.intro, image: a.image, sections: a.sections || [] })); } catch { return []; } };
const blank: Story = { slug: "", title: "", category: "Chăm hoa", intro: "", image: "tulip", sections: [] };
const readImage = (file: File) => new Promise<string>((resolve, reject) => { if (!/^image\/(jpeg|png|webp)$/.test(file.type)) return reject(new Error("Chỉ nhận ảnh JPEG, PNG hoặc WebP.")); if (file.size > 2500000) return reject(new Error("Ảnh tối đa 2,5MB.")); const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Không thể đọc ảnh.")); reader.readAsDataURL(file); });
export default function AdminStories() {
  const [items, setItems] = useState<Story[]>(read); const [editing, setEditing] = useState<Story | null>(null); const [error, setError] = useState("");
  const save = () => { if (!editing?.slug.trim() || !editing.title.trim()) return setError("Vui lòng nhập tiêu đề và đường dẫn."); const next = items.some((x) => x.slug === editing.slug) ? items.map((x) => x.slug === editing.slug ? editing : x) : [editing, ...items]; setItems(next); localStorage.setItem(KEY, JSON.stringify(next)); setEditing(null); setError(""); };
  const remove = (slug: string) => { if (!window.confirm("Xóa câu chuyện này?")) return; const next = items.filter((x) => x.slug !== slug); setItems(next); localStorage.setItem(KEY, JSON.stringify(next)); };
  const upload = (e: ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file || !editing) return; void readImage(file).then((image) => setEditing({ ...editing, image })).catch((e) => setError(e.message)); };
  return <><PageHeading eyebrow="QUẢN TRỊ NHÀ HOA" title="Câu chuyện" description="Quản lý nội dung xuất hiện trên trang Chuyện Nhà Hoa." /><section className="admin-layout wrap section-bottom"><AdminNav /><div className="admin-content"><div className="section-heading"><h2>Danh sách câu chuyện ({items.length})</h2><button className="button" onClick={() => { setEditing({ ...blank, slug: `cau-chuyen-${Date.now()}` }); setError(""); }}><Plus size={16} /> Thêm câu chuyện</button></div>{error && <p className="form-error" role="alert">{error}</p>}{editing && <div className="help-panel story-editor"><div className="story-editor-preview">{editing.image.startsWith("data:") ? <img src={editing.image} alt="Xem trước" /> : <img src={`/images/${editing.image}.jpg`} alt="Xem trước" />}<label className="button outline"><ImagePlus size={16} /> Đổi ảnh<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} /></label></div><div className="story-editor-fields"><label className="field">Tiêu đề<input value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} /></label><label className="field">Đường dẫn<input value={editing.slug} onChange={e => setEditing({ ...editing, slug: e.target.value })} /></label><label className="field">Chủ đề<input value={editing.category} onChange={e => setEditing({ ...editing, category: e.target.value })} /></label><label className="field full">Mô tả<textarea rows={4} value={editing.intro} onChange={e => setEditing({ ...editing, intro: e.target.value })} /></label><div className="story-editor-actions"><button className="button" type="button" onClick={save}>Lưu câu chuyện</button><button className="button outline" type="button" onClick={() => setEditing(null)}>Hủy</button></div></div></div>}<div className="story-admin-list">{items.map(item => <article className="story-admin-card" key={item.slug}><img src={item.image.startsWith("data:") ? item.image : `/images/${item.image}.jpg`} alt="" /><div><span className="eyebrow">{item.category}</span><h3>{item.title}</h3><p>{item.intro}</p></div><div className="story-admin-actions"><button className="icon-button admin-action-icon" aria-label="Sửa" onClick={() => setEditing(item)}><Pencil size={16} /></button><button className="icon-button admin-action-icon" aria-label="Xóa" onClick={() => remove(item.slug)}><Trash2 size={16} /></button></div></article>)}</div></div></section></>;
}
